name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          cache: true

      - name: Check Go version
        run: go version

      - name: Prepare dependencies
        run: |
          go mod tidy
          go mod download

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
